//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Game/PlayerInput/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace WhaleBoxTest.Game.PlayerInput
{
    public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""UniversalActionMap"",
            ""id"": ""6a8a38ee-675f-4680-956e-c161dd52729d"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a88738b6-6690-4496-bb2a-f4729cc31124"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""59b1d106-7f2b-449c-a230-29b96ea5931b"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // UniversalActionMap
            m_UniversalActionMap = asset.FindActionMap("UniversalActionMap", throwIfNotFound: true);
            m_UniversalActionMap_Jump = m_UniversalActionMap.FindAction("Jump", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // UniversalActionMap
        private readonly InputActionMap m_UniversalActionMap;
        private List<IUniversalActionMapActions> m_UniversalActionMapActionsCallbackInterfaces = new List<IUniversalActionMapActions>();
        private readonly InputAction m_UniversalActionMap_Jump;
        public struct UniversalActionMapActions
        {
            private @PlayerInputActions m_Wrapper;
            public UniversalActionMapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Jump => m_Wrapper.m_UniversalActionMap_Jump;
            public InputActionMap Get() { return m_Wrapper.m_UniversalActionMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UniversalActionMapActions set) { return set.Get(); }
            public void AddCallbacks(IUniversalActionMapActions instance)
            {
                if (instance == null || m_Wrapper.m_UniversalActionMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UniversalActionMapActionsCallbackInterfaces.Add(instance);
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }

            private void UnregisterCallbacks(IUniversalActionMapActions instance)
            {
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
            }

            public void RemoveCallbacks(IUniversalActionMapActions instance)
            {
                if (m_Wrapper.m_UniversalActionMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUniversalActionMapActions instance)
            {
                foreach (var item in m_Wrapper.m_UniversalActionMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UniversalActionMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UniversalActionMapActions @UniversalActionMap => new UniversalActionMapActions(this);
        public interface IUniversalActionMapActions
        {
            void OnJump(InputAction.CallbackContext context);
        }
    }
}
